server:
  port: ${PROT:8092}
spring:
  application:
    name: eurekaService

eureka:
  client:
    registerWithEureka: true #服务注册开关
    fetchRegistry: true #服务发现开关
    serviceUrl: #Eureka客户端与Eureka服务端进行交互的地址，多个中间用逗号分隔
      defaultZone: http://localhost:8091/eureka/,http://localhost:8089/eureka/
  instance:
    prefer-ip-address: true  #将自己的ip地址注册到Eureka服务中
    ip-address: ${ID_ADDRESS:127.0.0.2}
    instance-id: ${spring.application.name}:${server.port} #指定实例id